name: Release if needed

on:
  workflow_dispatch:
  push:
    -branches:
      - "!releases/**/*"
      - main

env:
  # Used by scripts/build-types.sh
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build application
        uses: ./.github/actions/build

  release:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Release if needed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        shell: bash
        run: yarn run shipjs trigger
